name: "Build LaTex Document"
on:
  push:
    branches:
      - main

env:
  OUTPUT_FILE: main.pdf
  BUILD_CMD: "just build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check
    - run: nix develop --command $BUILD_CMD
    - name: Bump version and push tag
      id: bump
      uses: anothrNick/github-tag-action@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
    - name: upload
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.bump.outputs.new_tag }}
        make_latest: true
        files: ${{ env.OUTPUT_FILE }}
